export const TOGGLE_MENU = "TOGGLE_MENU";

export const IS_ADMIN = "IS_ADMIN";
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const CREATE_MINI_PROJECT = 'CREATE_MINI_PROJECT';
export const FETCH_MINI_PROJECTS = 'FETCH_MINI_PROJECTS';
export const FETCH_MINI_PROJECT = 'FETCH_MINI_PROJECT';
export const EDIT_MINI_PROJECT = 'EDIT_MINI_PROJECT';
export const DELETE_MINI_PROJECT = 'DELETE_MINI_PROJECT';

export const CREATE_SKILL = 'CREATE_SKILL';
export const FETCH_SKILLS = 'FETCH_SKILLS';
export const FETCH_SKILL = 'FETCH_SKILL';
export const EDIT_SKILL = 'EDIT_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const FETCH_EXPERIENCE = 'FETCH_EXPERIENCE';
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';

export const CREATE_VOLUTEER_EXPERIENCE = 'CREATE_VOLUTEER_EXPERIENCE';
export const FETCH_VOLUTEER_EXPERIENCES = 'FETCH_VOLUTEER_EXPERIENCES';
export const FETCH_VOLUTEER_EXPERIENCE = 'FETCH_VOLUTEER_EXPERIENCE';
export const EDIT_VOLUTEER_EXPERIENCE = 'EDIT_VOLUTEER_EXPERIENCE';
export const DELETE_VOLUTEER_EXPERIENCE = 'DELETE_VOLUTEER_EXPERIENCE';

export const CREATE_CONTACT = 'CREATE_CONTACT';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const CREATE_MEETING = 'CREATE_MEETING';
export const FETCH_MEETINGS = 'FETCH_MEETINGS';
export const FETCH_MEETING = 'FETCH_MEETING';
export const EDIT_MEETING = 'EDIT_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';

export const CREATE_TESTIMONIAL = 'CREATE_TESTIMONIAL';
export const FETCH_TESTIMONIALS = 'FETCH_TESTIMONIALS';
export const FETCH_TESTIMONIAL = 'FETCH_TESTIMONIAL';
export const EDIT_TESTIMONIAL = 'EDIT_TESTIMONIAL';
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';

export const CREATE_CERTIFICATION = 'CREATE_CERTIFICATION';
export const FETCH_CERTIFICATIONS = 'FETCH_CERTIFICATIONS';
export const FETCH_CERTIFICATION = 'FETCH_CERTIFICATION';
export const EDIT_CERTIFICATION = 'EDIT_CERTIFICATION';
export const DELETE_CERTIFICATION = 'DELETE_CERTIFICATION';

export const TOGGLE_PROJECTS = 'TOGGLE_PROJECTS';
export const TOGGLE_MINI_PROJECTS = 'TOGGLE_MINI_PROJECTS';
export const TOGGLE_EXPERIENCE = 'TOGGLE_EXPERIENCE';