export const BooksReading = [
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    },
    {   id:'',
        bookName:'',
        bookLink:'',
        bookAuthor:'',
    }
    
]